if (NOT TARGET curl)
    find_package(PkgConfig)
    pkg_check_modules(libcurl REQUIRED libcurl>=8.8.0)
    include(FindPackageHandleStandardArgs)
    find_package_handle_standard_args(libcurl "libcurl not found; using internal version" libcurl_LIBRARIES libcurl_INCLUDE_DIRS)
    if (libcurl_FOUND)
        add_library(curl INTERFACE)
        target_link_libraries(curl INTERFACE ${libcurl_LIBRARIES})
        target_include_directories(curl INTERFACE ${libcurl_INCLUDE_DIRS})
        target_compile_options(curl INTERFACE ${libcurl_CFLAGS_OTHER})
        target_include_directories(curl INTERFACE $<BUILD_INTERFACE:${libcurl_INCLUDE_DIRS}>)
        add_library(libcurl ALIAS curl)
    endif()
endif()
